version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  event_data_base:
    image: postgres:13
    environment:
      - POSTGRES_DB=eventSourcing
      - POSTGRES_USER=eventSourcing
      - POSTGRES_PASSWORD=eventSourcing
    ports:
      - '5434:5432'
    volumes:
      - ~/data_volums_docker/postventa_database:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "vaxidrez"
      MONGO_INITDB_ROOT_PASSWORD: "VaxiDrez2005$$"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  default:
    name: bankingNetwork
